### ISSUE TITLE
TypeError: _ionic_native_sqlite__WEBPACK_IMPORTED_MODULE_4__.SQLite.create(...) is undefined

### ISSUE THREAD

**Issue by jlbgit** [alex-steinberg/ionic-react-sqlite-example#1]
Hi, 
I was trying your repo on Ubuntu 16.04 and Firefox, using

```
npm install
ionic serve
```
but I keep getting this TypeError:

![ErrorSQLite](https://user-images.githubusercontent.com/31538331/79137124-6b88ce80-7db2-11ea-9344-368d5f1be149.png)

Any idea why this happens? Or is it that I can't run this on a browser/PC?

Many thanks!
Jan

**Comment by alex-steinberg** [comment]
This will not work in the browser. If you run it on a device (as per the README) it should work.
